worker_processes  1;

events { worker_connections  1024; }

http {
  lua_package_path "/usr/local/openresty/nginx/lua/?.lua;;";

  server {
    listen 8080;

    location = /health {
      default_type application/json;
      return 200 '{"status":"ok","service":"openresty"}';
    }

    location = /api/v1/payment {
      content_by_lua_file /usr/local/openresty/nginx/lua/payment.lua;
    }

    location = /api/v1/webhook/payment {
      content_by_lua_file /usr/local/openresty/nginx/lua/webhook.lua;
    }
  }
}
