FROM python:3.10-slim
WORKDIR /app
COPY packages/requirements.txt .
RUN pip install -r requirements.txt
COPY packages/ .
COPY services/gateway/ .
EXPOSE 8090
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8090"]
